{% set ip = config_host if config_host not in ['127.0.0.1', 'localhost'] else baremetal_net|local_ip %}
{% set user = 'root' if config_user == 'apache' else config_user %}
kcli:
 type: {{ config_type }}
 host: {{ ip }}
{% if config_type == 'vsphere'  %}
 user: {{ config_user }}
 password: {{ config_password }}
 datacenter: {{ config_datacenter }}
 cluster: {{ config_cluster }}
 pool: {{ config_pool }}
{% else %}
 user: {{ user }}
 pool: {{ pool }}
{% endif %}
