{% import 'static_network/config.j2' as static_network %}
{% set baremetal_prefix = baremetal_cidr.split('/')[1] %}
{% set baremetal_gateway = static_baremetal_gateway or baremetal_cidr|network_ip(1 if lab else -2) %}
{% set baremetal_dns = static_baremetal_dns or baremetal_gateway %}
{% set nic = 'enp1s0' %}
{% set ipv6 =  api_ip != None and ':' in api_ip %}
{% if virtual_ctlplanes %}
{% set extra_ctlplanes = [] %}
{% for num in range(0, virtual_ctlplanes_number) %}
{% if virtual_ctlplanes_static_network and baremetal_ips|length > num %}
{% set new_ctlplane = {'ip': baremetal_ips[num]} %}
{% else %}
{% set new_ctlplane = {} %}
{% endif %}
{% do extra_ctlplanes.append(new_ctlplane) %}
{% endfor %}
{% set ctlplanes = extra_ctlplanes + ctlplanes %}
{% endif %}
{% if virtual_workers and virtual_workers_deploy %}
{% set extra_workers = [] %}
{% for num in range(0, virtual_workers_number) %}
{% if virtual_workers_static_network and baremetal_ips|length > virtual_ctlplanes_number + num %}
{% set new_worker = {'ip': baremetal_ips[virtual_ctlplanes_number + num]} %}
{% else %}
{% set new_worker = {} %}
{% endif %}
{% do extra_workers.append(new_worker) %}
{% endfor %}
{% set workers = extra_workers + workers %}
{% endif %}
{% set virtual_ctlplanes_bootmac_prefix = virtual_ctlplanes_baremetal_mac_prefix %}
{% set virtual_workers_bootmac_prefix = virtual_workers_baremetal_mac_prefix %}
{% set cluster_network_ipv6 = {"cidr": "fd01::/48", "hostPrefix": 64} %}
{% set cluster_network_ipv4 = {"cidr": "10.132.0.0/14", "hostPrefix": 23} %}
{% set service_network_ipv6 = ["fd02::/112"] %}
{% set service_network_ipv4 = ["172.30.0.0/16"] %}
{% set machine_networks = [baremetal_cidr] %}
{% set api_vips = [api_ip] %}
{% if dual_api_ip != None and ':' in dual_api_ip %}
{% set dualstack = True %}
{{ api_vips.append(dual_api_ip)|default("", True) }}
{% endif %}
{% set ingress_vips = [ingress_ip] %}
{% if dual_ingress_ip != None and ':' in dual_ingress_ip %}
{{ ingress_vips.append(dual_ingress_ip)|default("", True) }}
{% endif %}
{% if dualstack|default(False) %}
{% set machine_networks = [baremetal_cidr] + [dualstack_cidr] %}
{% set cluster_networks = [cluster_network_ipv4] + [cluster_network_ipv6] %}
{% set service_networks = service_network_ipv4 + service_network_ipv6 %}
{% elif ipv6 %}
{% set cluster_networks = [cluster_network_ipv6] %}
{% set service_networks = service_network_ipv6 %}
{% else %}
{% set cluster_networks = [cluster_network_ipv4] %}
{% set service_networks = service_network_ipv4 %}
{% endif %}
{% set libvirt_user =  'root' if config_user == 'apache' else config_user %}
{% set libvirt_ip = config_host if config_host not in ['127.0.0.1', 'localhost'] else baremetal_net|local_ip %}
{% set libvirt_ip = libvirt_ip|replace(':', '-') + '.sslip.io' %}
{% set libvirt_url = 'qemu+ssh://' + libvirt_user + '@' + libvirt_ip + '/system' %}
apiVersion: v1
{% if fips %}
fips: True
{% endif %}
{% if cpu_partitioning %}
CPUPartitioningMode: AllNodes
{% endif %}
baseDomain: {{ domain }}
{% if http_proxy != None %}
proxy:
    httpProxy: {{ 'http://' + http_proxy if 'http' not in http_proxy else http_proxy }}
    httpsProxy: {{ 'http://' + http_proxy if 'http' not in http_proxy else http_proxy }}
{% if no_proxy != None %}
    noProxy: {{ no_proxy }}
{% else  %}
    noProxy: {{ baremetal_cidr }}
{% endif %}
{% endif %}
networking:
  networkType: {{ network_type }}
  machineNetwork:
{% for network in machine_networks %}
  - cidr: {{ network }}
{% endfor %}
  clusterNetwork:
{% for network in cluster_networks %}
  - cidr: {{ network['cidr'] }}
    hostPrefix: {{ network['hostPrefix'] }}
{% endfor %}
  serviceNetwork:
{% for network in service_networks %}
  - {{ network }}
{% endfor %}
metadata:
  name: {{ cluster }}
compute:
- name: worker
  replicas: {{ workers|length }}
controlPlane:
  name: master
  replicas: {{ ctlplanes|length }}
platform:
  baremetal:
    apiVIPs:
{% for api_vip in api_vips %}
    - {{ api_vip }}
{% endfor %}
    ingressVIPs:
{% for ingress_vip in ingress_vips %}
    - {{ ingress_vip }}
{% endfor %}
{% if baremetal_bootstrap_os_image != None %}
    bootstrapOSImage: {{ baremetal_bootstrap_os_image }}
{% endif %}
{% if baremetal_cluster_os_image != None %}
    clusterOSImage: {{ baremetal_cluster_os_image }}
{% endif %}
    provisioningNetwork: "Disabled"
{% if baremetal_noprovisioning_ip != None %}
    provisioningHostIP: {{ baremetal_noprovisioning_ip }}
{% endif %}
{% if baremetal_noprovisioning_bootstrap_ip != None %}
    bootstrapProvisioningIP: {{ baremetal_noprovisioning_bootstrap_ip }}
{% endif %}
    externalBridge: {{ baremetal_net }}
    libvirtURI: {{ libvirt_url }}
{% if baremetal_bootstrap_mac != None %}
    externalMACAddress: {{ baremetal_bootstrap_mac }}
{% endif %}
    hosts:
{% for ctlplane in ctlplanes %}
{% set num = loop.index0|string %}
    - name: {{ cluster }}-ctlplane-{{ num }}
      role: master
      bmc:
        {% if 'redfish_address' in ctlplane %}
        disableCertificateVerification: True
        {% if 'redfish' in ctlplane['redfish_address'] or 'idrac' in ctlplane['redfish_address'] %}
        address: {{ ctlplane['redfish_address'] }}
        {% elif ctlplane['model']|default(model) in ['hp', 'hpe', 'supermicro'] %}
        address: redfish-virtualmedia://{{ ctlplane['redfish_address'] }}/redfish/v1/Systems/1
        {% else %}
        address: idrac-virtualmedia://{{ ctlplane['redfish_address'] }}/redfish/v1/Systems/System.Embedded.1
        {% endif %}
        {% else %}
        address: redfish-virtualmedia+http://CHANGEME:9000/redfish/v1/Systems/kcli/{{ cluster }}-ctlplane-{{ num }}
        {% endif %}
        username: {{ ctlplane['bmc_user']|default(bmc_user) }}
        password: {{ ctlplane['bmc_password']|default(bmc_password) }}
{% if 'boot_mode' in ctlplane %}
      bootMode: {{ ctlplane['boot_mode'] }}
{% endif %}
{% if 'provisioning_mac' in ctlplane %}
      bootMACAddress: {{ ctlplane['provisioning_mac'] }}
{% elif baremetal_macs and baremetal_macs|length > num|int %}
      bootMACAddress: {{ baremetal_macs[num|int] }}
{% else %}
      bootMACAddress: {{ virtual_ctlplanes_bootmac_prefix + ":" + "%02.d" | format(num|int + 1)| string }}
{% endif %}
      {% if 'disk' in ctlplane %}
      rootDeviceHints:
        deviceName: "/dev/{{ ctlplane['disk'] | basename }}"
      {% elif 'hctl' in ctlplane %}
      rootDeviceHints:
        hctl: "{{ ctlplane['hctl'] }}"
      {% elif 'serial' in ctlplane %}
      rootDeviceHints:
        serialNumber: "{{ ctlplane['serial'] }}"
      {% elif 'wwn' in ctlplane %}
      rootDeviceHints:
        wwn: "{{ ctlplane['wwn'] }}"
      {% endif %}
      {% if 'ip' in ctlplane %}
      networkConfig:
        {{ static_network.config(ctlplane['ip'], baremetal_prefix, ctlplane['gateway']|default(baremetal_gateway), ctlplane['dns']|default(baremetal_dns), cluster, domain, ctlplane['nic']|default(nic)) }}
      {% elif 'network_config' in ctlplane %}
      networkConfig:
        {{ ctlplane['network_config']|replace('\n', '\n        ') }}
      {% endif %}
{% endfor %}
{% for worker in workers %}
{% set num = loop.index0|string %}
    - name: {{ cluster }}-worker-{{ num }}
      role: worker
      bmc:
        {% if 'redfish_address' in worker %}
        disableCertificateVerification: True
        {% if 'redfish' in worker['redfish_address'] or 'idrac' in worker['redfish_address'] or 'ilo5' in worker['redfish_address'] %}
        address: {{ worker['redfish_address'] }}
        {% elif worker['model']|default(model) in ['hp', 'hpe', 'supermicro'] %}
        address: redfish-virtualmedia://{{ worker['redfish_address'] }}/redfish/v1/Systems/1
        {% else %}
        address: idrac-virtualmedia://{{ worker['redfish_address'] }}/redfish/v1/Systems/System.Embedded.1
        {% endif %}
        {% else %}
        address: redfish-virtualmedia+http://CHANGEME:9000/redfish/v1/Systems/kcli/{{ cluster }}-worker-{{ num }}
        {% endif %}
        username: {{ worker['bmc_user']|default(bmc_user) }}
        password: {{ worker['bmc_password']|default(bmc_password) }}
{% if 'boot_mode' in worker %}
      bootMode: {{ worker['boot_mode'] }}
{% endif %}
{% if 'provisioning_mac' in worker %}
      bootMACAddress: {{ worker ['provisioning_mac'] }}
{% elif baremetal_macs and baremetal_macs|length > virtual_ctlplanes_number + num|int %}
      bootMACAddress: {{ baremetal_macs[virtual_ctlplanes_number + num|int] }}
{% else %}
      bootMACAddress: {{ virtual_workers_bootmac_prefix + ":" + "%02.d" | format(num|int + 1)| string }}
{% endif %}
      hardwareProfile: {{ worker['profile']|default('unknown') }}
      {% if 'disk' in worker %}
      rootDeviceHints:
        deviceName: "/dev/{{ worker['disk'] | basename }}"
      {% elif 'hctl' in worker %}
      rootDeviceHints:
        hctl: "{{ worker['hctl'] }}"
      {% elif 'serial' in worker %}
      rootDeviceHints:
        serialNumber: "{{ worker['serial'] }}"
      {% elif 'wwn' in worker %}
      rootDeviceHints:
        wwn: "{{ worker['wwn'] }}"
      {% endif %}
      {% if 'ip' in worker %}
      networkConfig:
        {{ static_network.config(worker['ip'], baremetal_prefix, worker['gateway']|default(baremetal_gateway), worker['dns']|default(baremetal_dns), cluster, domain, worker['nic']|default(nic)) }}
      {% elif 'network_config' in worker %}
      networkConfig:
        {{ worker['network_config']|replace('\n', '\n        ') }}
      {% endif %}
{% endfor %}
{% if cas %}
additionalTrustBundle: |
{% for ca in cas %}
 {{ ca | certificate | replace('\n', '\n ') }}
{% endfor %}
{% endif %}
{% if imagecontentsources %}
imageContentSources:
{% for source in imagecontentsources %}
- mirrors:
  - {{ source }}
  source: image-registry.openshift-image-registry.svc:5000/openshift/{{ source | basename | replace("openshift-", "")}}
{% endfor %}
{% endif %}
