{% set cluster_network_ipv6 = {"cidr": "fd01::/48", "hostPrefix": 64} %}
{% set cluster_network_ipv4 = {"cidr": "10.132.0.0/14", "hostPrefix": 23} %}
{% set service_network_ipv6 = ["fd02::/112"] %}
{% set service_network_ipv4 = ["172.30.0.0/16"] %}
{% if dualstack|default(False) %}
{% set cluster_networks = [cluster_network_ipv4] + [cluster_network_ipv6] %}
{% set service_networks = service_network_ipv4 + service_network_ipv6 %}
{% elif ipv6|default(False) or (api_ip is defined and ':' in api_ip) %}
{% set cluster_networks = [cluster_network_ipv6] %}
{% set service_networks = service_network_ipv6 %}
{% else %}
{% set cluster_networks = [cluster_network_ipv4] %}
{% set service_networks = service_network_ipv4 %}
{% endif %}

{% set virtual_ctlplanes_nodes = [] %}
{% set virtual_workers_nodes = [] %}
{% if virtual_ctlplanes %}
{% for num in range(0, virtual_ctlplanes_number) %}
{% do virtual_ctlplanes_nodes.append({}) %}
{% endfor %}
{% endif %}
{% if virtual_workers and virtual_workers_deploy %}
{% for num in range(0, virtual_workers_number) %}
{% do virtual_workers_nodes.append({}) %}
{% endfor %}
{% endif %}
{% set hosts = ctlplanes + virtual_ctlplanes_nodes + workers + virtual_workers_nodes %}

apiVersion: v1
{% if cpu_partitioning %}
CPUPartitioningMode: AllNodes
{% endif %}
baseDomain: {{ domain }}
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  replicas: {{ (workers + virtual_workers_nodes)|length }}
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: {{ (ctlplanes + virtual_ctlplanes_nodes)|length }}
metadata:
  name: {{ cluster }}
networking:
  clusterNetwork:
{% for network in cluster_networks %}
  - cidr: {{ network.cidr }}
    hostPrefix: {{ network.hostPrefix }}
{% endfor %}
  machineNetwork:
{% for network in [baremetal_cidr] %}
  - cidr: {{ network }}
{% endfor %}
  networkType: {{ network_type|default("OVNKubernetes") }}
  serviceNetwork:
{% for network in service_networks %}
  - {{ network }}
{% endfor %}
platform:
{% if hosts|length == 1 %}
  none: {}
{% else %}
  baremetal:
    apiVips:
    - {{ api_ip }}
    hosts:
{% for host in hosts %}
    - name: {{ host['name']|default(cluster + "-" + loop.index0|string) }}
{% if 'mac' in host %}
      bootMACAddress: {{ host['mac'] }}
{% endif %}
      role: {{ host['role']|default('master' if loop.index0 < 3 else 'worker') }}
{% endfor %}
    ingressVips:
    - {{ ingress_ip }}
{% endif %}
{% if cas %}
additionalTrustBundle: |
{% for ca in cas %}
 {{ ca | certificate | replace('\n', '\n ') }}
{% endfor %}
{% endif %}
{% if imagecontentsources %}
imageContentSources:
{% for source in imagecontentsources %}
- mirrors:
  - {{ source }}
  source: image-registry.openshift-image-registry.svc:5000/openshift/{{ source | basename | replace("openshift-", "")}}
{% endfor %}
{% endif %}
