cluster: emmet
domain: brown.com
version: stable
tag: 4.10
bmc_user: marty
bmc_password: mcfly
baremetal_cidr: 11.0.0.0/24
api_ip: 11.0.0.2
ingress_ip: 11.0.0.4
virtual_hub: False
baremetal_ctlplanes:
- redfish_address: 10.0.0.1
  mac: aa:aa:aa:bb:cc:01
- redfish_address: 10.0.0.2
  mac: aa:aa:aa:bb:cc:02
- redfish_address: 10.0.0.3
  mac: aa:aa:aa:bb:cc:03
baremetal_workers:
- redfish_address: 10.0.0.4
  mac: aa:aa:aa:bb:cc:04
