---
apiVersion: v1
kind: ConfigMap
metadata:
  name: group-hardware-types-configmap
  namespace: ztp-policies
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
data:
  # PerformanceProfile.yaml
  hw-type-platform-1-cpu-isolated: "4-15"
  hw-type-platform-1-cpu-reserved: "0-3"
  hw-type-platform-1-hugepages-default: "1G"
  hw-type-platform-1-hugepages-count: "16"
  hw-type-platform-1-hugepages-size: "1G"
  hw-type-platform-1-supported-sriov-nic: "false"
  hw-type-platform-1-storage-path: "/dev/sdb"
